[tool.poetry]
name = "duplicateimages"
version = "0.1.0"
description = ""
authors = ["Lene Preuss <lene.preuss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
